### ISSUE TITLE
Ошибка The CAPTCHA thinks you are a robot! при попытки авторизоваться 

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#10]
**Шаги:**
1. Открыть страницу авторизации
2. Ввести неверный логин или пароль 
3. Нажать Sign in
4. Повторить пункты 2, 3 с верными данными

**ОР:**
Произойдет вход в аккаунт 

**ФР:**
Ошибка The CAPTCHA thinks you are a robot! Please refresh and try again.

Env:
Win10, Chrome 121.0.6167.140

Screenshots:
![2024-02-02_14-12-24](https://github.com/yahannes/FinTrack/assets/69787064/50d28d18-84e3-495a-873c-eb2ae517a4a0)

**Comment by yahannes** [comment]
Проблема в том, что если перевести данное сообщение, то капча думает, что вы робот :)

**Comment by yahannes** [comment]
Пофикшено

**Comment by yahannes** [comment]
Баг поифкшен
