### ISSUE TITLE
Ошибка 500 SERVER ERROR, при попытки выполнить регистрацию 

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#12]
**Шаги:**
1. Открыть страницу регистрации 
2. Заполнить поля
3. Нажать Sign up

**ОР:**
Регистрация выполнена успешно
 
**ФР:**
Ошибка 500 500 SERVER ERROR

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![2024-02-04_05-52-06](https://github.com/yahannes/FinTrack/assets/69787064/e6c5bb6e-54cc-4bee-a418-b51ca9e5d18c)

**Comment by yahannes** [comment]
Bug Fixed
