### ISSUE TITLE
Добавить функцию позволяющую вернуться со страницы Create company

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#15]
На данный момент не возможно без кнопок браузера "Назад" вернуться со страницы Create company и Profile, что очень неудобно. 

![image](https://github.com/yahannes/FinTrack/assets/69787064/82e861db-56b3-412b-a447-958cb936eca4)
![image](https://github.com/yahannes/FinTrack/assets/69787064/07ed6474-9335-4ef0-bd71-340c2f8deebd)

**Comment by yahannes** [comment]
Фишка внедрена
