### ISSUE TITLE
Ошибка 500 SERVER ERROR, при создании двух компаний с одинаковыми именами

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#17]
**Шаги:**
1. Открыть страницу Create company
2. Создать 2 компании с одинаковым значением в поле Name

**ОР:**
Ошибка указывающая на уже существующую компании с таким именем

**ФР:**
Ошибка 500 SERVER ERROR

**Screenshots:**
![2024-02-04_09-46-39](https://github.com/yahannes/FinTrack/assets/69787064/714727a8-7c86-43fa-b298-a9bfb96d2f30)

**Comment by yahannes** [comment]
Bug fixed
