### ISSUE TITLE
Ошибка 500 SERVER ERROR, при создании уже существующего контакта на странице Create Contact

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#18]
**Шаги:**
1. Перейти на страницу Create Contact
2. Создать контакт с данными, уже существующего контакта

**ОР:** 
Отображается ошибка, об уже созданном контакте, с такими же значениями для каждого поля

**ФР:**
Ошибка 500 SERVER ERROR

**Comment by yahannes** [comment]
Bug Fixed
