### ISSUE TITLE
Созданные Sales не отображаются в статистике на странице Dashboard

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#19]
**Шаги**
1.  Перейти на страницу Create Sale
2. Заполнить поля
3. Нажать Create
4. Перейти на страницу Dashboard -> график Sales

**ОР:**
На графике отображаются количество созданных Sales

**ФР:**
На графике отображается 0 созданных Sales

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/5394ffcc-ea23-4121-842b-804c4a06dd71)

**Comment by yahannes** [comment]
Bug fixed
