### ISSUE TITLE
404 NOT FOUND, при попытки изменить Short name на странице Edit company

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#20]
**Шаги:**
1. Открыть страницу Edit company
2. Изменить значение в поле Short name
3. Сохранить изменения

**ОР:**
Изменения успешно сохранены

**ФР:**
404 NOT FOUND

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/066fcee6-bb1f-4af5-8922-cc38f79934bf)

**Comment by yahannes** [comment]
Прочитайте вопрос #11 пожалуйста
