### ISSUE TITLE
Отсутствует строка поиска на страницах Payments, Requisites, Warehouses, Stuff Statements

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#21]
**Шаги:**
1. Открыть страницы Payments, Requisites, Warehouses, Stuff Statements

**ОР:**
Строка поиска отображается на всех страницах

**ФР:**
Строка поиска отсутствует

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/eefd6888-426f-4123-8a91-dab3ae54fdb3)

**Comment by yahannes** [comment]
flaw  fixed
