### ISSUE TITLE
Неверный текст ошибки в поле "Адрес электронной почты" на этапе регистрации

### ISSUE THREAD

**Issue by bobkofi** [yahannes/FinTrack#22]
Шаги:
Зайти в раздел "Регистрация учетной записи"
Заполнить поле "Адрес электронной почты"
Нажать кнопку "Зарегистрироваться"

ОР:
Текст ошибки:"Должен быть указан существующий адрес электронной почты".

ФР:
Текст ошибки: "The адрес электронной почты field must be a valid email address."

Среда:
Windows 11, Yandex Версия 24.1.0.2570 (64-bit)

Приложение:
![The адрес электронной почты](https://github.com/yahannes/FinTrack/assets/132677222/0b93dc23-c0df-4cbe-8669-4ed266b8c756)

**Comment by yahannes** [comment]
Bug fixed
