### ISSUE TITLE
Purchases, Sales можно привязать к складу другой компании 

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#24]
**Пред.Условия:**
1. На аккаунте должно быть создано 2 компании
2. У каждой компании создан склад

**Шаги:**
1. Открыть страницу Create Purchase, Create Sale
3. Выбрать поле Warehouse

**ОР:**
В поле Warehouse отображаются склады принадлежащие только выбранной компании

**ФР:**
В поле Warehouse отображаются все созданные склады на аккаунте 

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/58c1d465-3511-43cc-bee9-064842bd34d2)
![image](https://github.com/yahannes/FinTrack/assets/69787064/bacf1e32-fd7c-4366-a438-5e1e36d7e2ca)

**Comment by yahannes** [comment]
bug fixed
