### ISSUE TITLE
Ошибка 500 SERVER ERROR, при превышение количество символов в полях на странице Create Purchase/Edit Purchase

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#25]
**Пред. Условие:**
1. Создан Warehouse

**Шаги:**
1. Открыть страницу Create Purchase/Edit Purchase
2. В полях **Quantity**, **Price**, **Summary** ввести значение из 256+ символов

**ОР:**
Сообщение об ошибке, сообщающие о превышении количества символов

**ФР:**
Ошибка 500 SERVER ERROR

**Env:**
Win10, Chrome 121.0.6167.139

**Comment by yahannes** [comment]
validation fixed
