### ISSUE TITLE
На новом аккаунте не нулевая статистика 

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#26]
**Шаги:**
1. Зарегистрировать новый аккаунт
2. Открыть страницу Dashboard

**ОР:**
На странице Dashboard отображается пустая статистика

**ФР:**
На странице Dashboard отображается статистика 

**Env:**
Win10, Chrome 121.0.6167.139

Screen
![image](https://github.com/yahannes/FinTrack/assets/69787064/64025aa2-ba39-4679-b3c4-c4757b9f9c6e)

**Comment by yahannes** [comment]
Bug fixed
