### ISSUE TITLE
Ошибка 500 SERVER ERROR, при создании Staff с номером состоящим из 9 цифр или меньше

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#27]
**Шаги:**
1. Открыть страницу Create Stuff
2. В поле Phone ввести значение из 9 цифр
3. Заполнить остальные поля
4. Нажать Create

**ОР:**
Сообщение об ошибке, с текстом "The number field must have at least 10 digits."

**ФР:**
Ошибка 500 SERVER ERROR

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/177a7b34-ae0c-43df-b833-eda2c2191c3b)

**Comment by zomlik** [comment]
По какой то причине периодически не получается сохранить номер из 10 цифр. Сохраняется только 9

**Comment by yahannes** [comment]
Bug fixed
