### ISSUE TITLE
Ошибка 500 SERVER ERROR при создании Stuff с уже созданными данными

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#28]
**Шаги:**
1. Перейти в Create Stuff 
2. Заполнить поля 
3. Нажать Create
4. Повторить шаги 1-3 с идентичными значениями 

**ОР:**
Ошибка с сообщением что Staff с указанными данными уже существует только для полей **Phone**, **Email**
Для остальных полей проверки быть не должно 

**ФР:**
Ошибка 500 SERVER ERROR

Env:
Win10, Chrome 121.0.6167.139

**Comment by yahannes** [comment]
Bug fixed
