### ISSUE TITLE
Имя пользователя вылезает за приделы блока на странице Lock Screen

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#3]
**Шаги:**
1. Открыть страницу "My Profile"
2. Установить имя в поле "Name" длинной ~80 символов
3. Перейти на страницу "Lock Screen"

**ОР:**
Имя не помещается в выделенной для него область

**ФР:**
Имя остается в пределах выделенной для него области

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![2024-02-02_06-30-20](https://github.com/yahannes/FinTrack/assets/69787064/40825b95-0cd2-4c87-a18e-fda76bef52c6)

**Comment by yahannes** [comment]
Пофикшено
