### ISSUE TITLE
Невозможно отредактировать созданный контакт

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#30]
**Шаги:**
1. Создать контакт
2. Нажать Edit
3. Изменить значение в одном из полей 
4. Сохранить изменение

**ОР:**
Изменение успешно сохранено

**ФР:**
Ошибка "The email has already been taken"

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/fcb366b0-334c-46fc-8b4a-22758fd7fede)

**Comment by yahannes** [comment]
Bug fixed
