### ISSUE TITLE
На странице Create Extract в поле Payment отображаются все опции из БД

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#31]
**Шаги:**
1. Перейти на страницу Create Extract
2. Нажать на поле Payment

**ОР:**
В поле отображаются Payment только выбранной компании если они есть

**ФР**
В поле отображаются все Payment из БД

**Env:**
Win10, Chrome 122.0.6261.94

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/53314b73-dc35-41af-b892-89ef1cc6cb50)

**Comment by yahannes** [comment]
bug fixed
