### ISSUE TITLE
Ошибка 500 SERVER ERROR после выбора пункта  Select an option в поле Type на странице Edit Company/Create Company

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#4]
**Шаги:**
1. Нажать на имя компании в верху меню
2. Выбрать пункт "Edit company"
3. Выбрать Type -> Select an option
4. Нажать Save changes 

**ОР:**
Отобразиться ошибка о необходимости выбрать тип компании

**ФР:**
Ошибка 500 SERVER ERROR

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![2024-02-02_07-16-03](https://github.com/yahannes/FinTrack/assets/69787064/e148a69b-1966-4faf-909d-5f315b660985)

**Comment by yahannes** [comment]
Пофикшено
