### ISSUE TITLE
Ошибка 404 NOT FOUND при использовании одинакового имени в поле Name и Short name на странице Edit Company 

### ISSUE THREAD

**Issue by zomlik** [yahannes/FinTrack#5]
**Шаги:**
1. Нажать на имя компании в меню
2. Выбрать Edit company
3. В поле Type выбрать один из пунктов
4. В поле Name и Short name ввести одинаковые значения
5. Нажать Save changes

**ОР:**
Данные будут сохранены

**ФР:**
Ошибка 404 NOT FOUND

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![2024-02-02_07-52-46](https://github.com/yahannes/FinTrack/assets/69787064/2c434622-2ae9-4940-a55c-0f4b0e08ac76)

**Comment by yahannes** [comment]
Данный баг на этапе альфа разработки очень трудно исправить так как, short_name используется в ссылке, например /dashboard/ваш-short-name/my-profile. Ошибка будет исправлена,но не сейчас, пока рекомендую после смены short_name перейти по ссылке : https://fintrack.space/dashboard
