### ISSUE TITLE
Нет кнопки включающей отображение пароля на этапе регистрации

### ISSUE THREAD

**Issue by bobkofi** [yahannes/FinTrack#8]
Шаги:

1. Зайти в раздел регистрации.
2. Заполнить поле "Пароль".
3. Заполнить поле "Подтвердите пароль".

ОР:
Есть значок в виде глазика, включающий отображение пароля.

ФР:
Нет значка в виде глазика, включающего отображение пароля.

Среда:
Windows 11, Yandex Browser Версия 24.1.0.2570 (64-bit)

Приложение:
![Нет глазика](https://github.com/yahannes/FinTrack/assets/132677222/cb6045c2-b4cc-4975-b197-7afcbb0d2b8b)
![Есть глазик](https://github.com/yahannes/FinTrack/assets/132677222/476c405e-9ef7-47d8-8002-05fbbbe09df4)

**Comment by yahannes** [comment]
Function added
