### ISSUE TITLE
Нет кнопки включающей отображение пароля на этапе авторизации

### ISSUE THREAD

**Issue by bobkofi** [yahannes/FinTrack#9]
1. Зайти в раздел авторизации.
2. Ввести пароль.

ОР:
Есть значок в виде глазика, включающий отображение пароля.

ФР:
Нет значка в виде глазика, включающего отображение пароля.

Среда:
Windows 11, Yandex Browser Версия 24.1.0.2570 (64-bit)

Приложение:
![Нет глазика на авторизации](https://github.com/yahannes/FinTrack/assets/132677222/fc3c54e9-9d08-4a32-b887-4f9f8919b048)
![Есть глазик](https://github.com/yahannes/FinTrack/assets/132677222/db92a7f6-9f99-4327-b350-abf225f55285)

**Comment by yahannes** [comment]
Function added
